// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComplejoDeportivo.Domain;

public partial class TipoSuperficie
{
    public int TipoSuperficieId { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Cancha> Canchas { get; set; } = new List<Cancha>();
}